FROM registry.access.redhat.com/ubi8/ubi
USER root
ADD wipe.py /usr/local/bin
RUN PKGS="python36 python3-requests" && yum install -y --setopt=tsflags=nodocs $PKGS && yum clean all && rpm -V $PKGS
ENTRYPOINT python3 /usr/local/bin/wipe.py -ip $IP -u $USERNAME -p $PASSWORD -t $TYPE
